package com.cjlu.ui;

import com.cjlu.controller.CourseController;
import com.cjlu.controller.Impl.CourseControllerImpl;
import com.cjlu.dao.CourseDao;
import com.cjlu.dao.impl.CourseDaoImpl;
import com.cjlu.entity.Course;
import com.cjlu.service.CourseService;
import com.cjlu.service.impl.CourseServiceImpl;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.awt.CardLayout;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 24825
 */
public class CourseManagerFrame extends javax.swing.JFrame {
    // 日志记录器
    private static final Logger logger = LoggerFactory.getLogger(CourseManagerFrame.class);
    //注入Controller层
    private final CourseController courseController;
    //表格模型
    private final DefaultTableModel tableModel;

    /**
     * Creates new form CourseManagerFrame
     */
    public CourseManagerFrame() {
        initComponents();
        //初始化Service层和模型
        CourseDao courseDao=new CourseDaoImpl();//将Dao层放到这里是什么意思呢？
        CourseService courseService = new CourseServiceImpl(courseDao);
        this.courseController = new CourseControllerImpl(courseService);
        this.tableModel =(DefaultTableModel) TableCourse.getModel();
        //启动时加载所有课程数据
        try {
            courseController.initCourseTable();
            refreshTable(courseController.loadAllCourse());
        } catch (Exception e) {
            logger.error("初始化课程数据失败", e);
            JOptionPane.showMessageDialog(this, "初始化课程数据失败：" + e.getMessage(), "错误", JOptionPane.ERROR_MESSAGE);
        }
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        CardPanel1 = new javax.swing.JPanel();
        ListCard = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnListCheck = new javax.swing.JButton();
        btnListAdd = new javax.swing.JButton();
        btnListUpdate = new javax.swing.JButton();
        btnListDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCourse = new javax.swing.JTable();
        AddCard = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCourseID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCourseCredit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCourseTeacher = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCourseSemester = new javax.swing.JTextField();
        btnAddBack = new javax.swing.JButton();
        btnAddSave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        UpdateCard = new javax.swing.JPanel();
        UPDATE = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtCourseID1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCourseName1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCourseCredit1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCourseTeacher1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCourseSemester1 = new javax.swing.JTextField();
        btnAddBack1 = new javax.swing.JButton();
        btnAddSave1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        // 关闭本窗口时仅隐藏窗口，保持系统运行
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        CardPanel1.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Search:");

        btnListCheck.setText("Check");
        btnListCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCheckActionPerformed(evt);
            }
        });

        btnListAdd.setText("Add");
        btnListAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListAddActionPerformed(evt);
            }
        });

        btnListUpdate.setText("Update");
        btnListUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListUpdateActionPerformed(evt);
            }
        });

        btnListDelete.setText("Delete");
        btnListDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListDeleteActionPerformed(evt);
            }
        });

        TableCourse.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "CourseID", "CourseName", "Credit", "Teacher", "Semester"
                }
        ));
        jScrollPane1.setViewportView(TableCourse);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
                TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(TopPanelLayout.createSequentialGroup()
                                                .addContainerGap(100, Short.MAX_VALUE)
                                                .addComponent(btnListAdd)
                                                .addGap(37, 37, 37)
                                                .addComponent(btnListUpdate)
                                                .addGap(31, 31, 31)
                                                .addComponent(btnListDelete))
                                        .addGroup(TopPanelLayout.createSequentialGroup()
                                                .addGap(56, 56, 56)
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListCheck)
                                .addGap(44, 44, 44))
                        .addGroup(TopPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopPanelLayout.setVerticalGroup(
                TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TopPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnListCheck)
                                        .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnListAdd)
                                        .addComponent(btnListUpdate)
                                        .addComponent(btnListDelete))
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout ListCardLayout = new javax.swing.GroupLayout(ListCard);
        ListCard.setLayout(ListCardLayout);
        ListCardLayout.setHorizontalGroup(
                ListCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TopPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ListCardLayout.setVerticalGroup(
                ListCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ListCardLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CardPanel1.add(ListCard, "list");

        jLabel2.setText("CourseID");

        txtCourseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseIDActionPerformed(evt);
            }
        });

        jLabel3.setText("CourseName");

        jLabel4.setText("Credit");

        jLabel5.setText("Teacher");

        jLabel6.setText("Semester");

        btnAddBack.setText("Back");
        btnAddBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBackActionPerformed(evt);
            }
        });

        btnAddSave.setText("Save");
        btnAddSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSaveActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel7.setText("ADD COURSE");

        javax.swing.GroupLayout AddCardLayout = new javax.swing.GroupLayout(AddCard);
        AddCard.setLayout(AddCardLayout);
        AddCardLayout.setHorizontalGroup(
                AddCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AddCardLayout.createSequentialGroup()
                                .addGroup(AddCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(AddCardLayout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(AddCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(AddCardLayout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addGap(1, 1, 1)
                                                                .addComponent(txtCourseName))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddCardLayout.createSequentialGroup()
                                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtCourseTeacher))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddCardLayout.createSequentialGroup()
                                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtCourseCredit))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddCardLayout.createSequentialGroup()
                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtCourseSemester))
                                                        .addGroup(AddCardLayout.createSequentialGroup()
                                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(AddCardLayout.createSequentialGroup()
                                                                .addGap(94, 94, 94)
                                                                .addComponent(btnAddSave, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnAddBack, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(62, 62, 62))))
                                        .addGroup(AddCardLayout.createSequentialGroup()
                                                .addGap(194, 194, 194)
                                                .addComponent(jLabel7)))
                                .addContainerGap(51, Short.MAX_VALUE))
        );
        AddCardLayout.setVerticalGroup(
                AddCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AddCardLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addGroup(AddCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(AddCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(AddCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(txtCourseCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(AddCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtCourseTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(AddCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(txtCourseSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(AddCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAddBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAddSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71))
        );

        CardPanel1.add(AddCard, "add");

        jLabel8.setText("CourseID");

        txtCourseID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseID1ActionPerformed(evt);
            }
        });

        jLabel9.setText("CourseName");

        jLabel10.setText("Credit");

        jLabel11.setText("Teacher");

        jLabel12.setText("Semester");

        btnAddBack1.setText("Back");
        btnAddBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBack1ActionPerformed(evt);
            }
        });

        btnAddSave1.setText("Update");
        btnAddSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSave1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel13.setText("UPDATE COURSE");

        javax.swing.GroupLayout UPDATELayout = new javax.swing.GroupLayout(UPDATE);
        UPDATE.setLayout(UPDATELayout);
        UPDATELayout.setHorizontalGroup(
                UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(UPDATELayout.createSequentialGroup()
                                .addGroup(UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(UPDATELayout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(UPDATELayout.createSequentialGroup()
                                                                .addComponent(jLabel9)
                                                                .addGap(1, 1, 1)
                                                                .addComponent(txtCourseName1))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UPDATELayout.createSequentialGroup()
                                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtCourseTeacher1))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UPDATELayout.createSequentialGroup()
                                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtCourseCredit1))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UPDATELayout.createSequentialGroup()
                                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtCourseSemester1))
                                                        .addGroup(UPDATELayout.createSequentialGroup()
                                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtCourseID1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(UPDATELayout.createSequentialGroup()
                                                                .addGap(94, 94, 94)
                                                                .addComponent(btnAddSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnAddBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(62, 62, 62))))
                                        .addGroup(UPDATELayout.createSequentialGroup()
                                                .addGap(174, 174, 174)
                                                .addComponent(jLabel13)))
                                .addContainerGap(51, Short.MAX_VALUE))
        );
        UPDATELayout.setVerticalGroup(
                UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(UPDATELayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addGroup(UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(txtCourseID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(txtCourseName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(txtCourseCredit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(txtCourseTeacher1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(txtCourseSemester1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAddBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAddSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout UpdateCardLayout = new javax.swing.GroupLayout(UpdateCard);
        UpdateCard.setLayout(UpdateCardLayout);
        UpdateCardLayout.setHorizontalGroup(
                UpdateCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 507, Short.MAX_VALUE)
                        .addGroup(UpdateCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(UpdateCardLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        UpdateCardLayout.setVerticalGroup(
                UpdateCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 448, Short.MAX_VALUE)
                        .addGroup(UpdateCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(UpdateCardLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );

        CardPanel1.add(UpdateCard, "update");

        getContentPane().add(CardPanel1, "card2");

        pack();
    }// </editor-fold>

    private void txtCourseIDActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnAddSaveActionPerformed(java.awt.event.ActionEvent evt) {
        // 获取输入数据
        String courseId = txtCourseID.getText().trim();
        String courseName = txtCourseName.getText().trim();
        String credit = txtCourseCredit.getText().trim();
        String teacher = txtCourseTeacher.getText().trim();
        String semester = txtCourseSemester.getText().trim();

        // 校验
        if (courseId.isEmpty() || courseName.isEmpty() || credit.isEmpty()|| teacher.isEmpty() || semester.isEmpty()) {
            JOptionPane.showMessageDialog(this, "必填项不能为空！");
            return;
        }

        if (!courseController.isNumber(credit)) {
            JOptionPane.showMessageDialog(this, "学分必须是数字！");
            return;
        }
        int credits = Integer.parseInt(credit);
        if (credits < 0) {
            JOptionPane.showMessageDialog(this, "学分不能为负数！");
            return;
        }

        // 封装Course对象
        Course course = new Course();
        course.setCourseId(courseId);
        course.setCourseName(courseName);
        course.setCredit(credits);
        course.setTeacher(teacher);
        course.setSemester(semester);

        try {
            // 调用Controller层新增课程
            String result = courseController.addCourse(course);
            if (!"添加成功".equals(result)) {
                JOptionPane.showMessageDialog(this, result, "提示", JOptionPane.WARNING_MESSAGE);
                return;
            }
            refreshTable(courseController.loadAllCourse());
            JOptionPane.showMessageDialog(this, result);
            // 切回列表卡片
            CardLayout cl = (CardLayout) CardPanel1.getLayout();
            cl.show(CardPanel1, "list");
            logger.info("新增课程成功，课程号：{}", courseId);
        } catch (Exception e) {
            logger.error("新增课程失败，课程号：{}", courseId, e);
            JOptionPane.showMessageDialog(this, "新增课程失败：" + e.getMessage(), "错误", JOptionPane.ERROR_MESSAGE);
        }
    }


    private void txtCourseID1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    //这个方法用于处理修改课程的保存按钮点击事件
    private void btnAddSave1ActionPerformed(java.awt.event.ActionEvent evt) {
        // 获取修改后的数据
        String courseId = txtCourseID1.getText().trim();
        String courseName = txtCourseName1.getText().trim();
        String credit = txtCourseCredit1.getText().trim();
        String teacher = txtCourseTeacher1.getText().trim();
        String semester = txtCourseSemester1.getText().trim();

        // 校验
        if (courseName.isEmpty() || credit.isEmpty()) {
            JOptionPane.showMessageDialog(this, "必填项不能为空！");
            return;
        }
        if (!courseController.isNumber(credit)) {
            JOptionPane.showMessageDialog(this, "学分必须是数字！");
            return;
        }
        int credits = Integer.parseInt(credit);
        if (credits < 0) {
            JOptionPane.showMessageDialog(this, "学分不能为负数！");
            return;
        }


        // 更新表格选中行
        int selectedRow = TableCourse.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "请先选择要修改的课程！");
            return;
        }

        // 封装Course对象
        Course course = new Course();
        course.setCourseId(courseId);
        course.setCourseName(courseName);
        course.setCredit(credits);
        course.setTeacher(teacher);
        course.setSemester(semester);

        try {
            // 调用Controller层更新课程
            String result = courseController.updateCourse(course);
            if (!result.contains("成功")) {
                JOptionPane.showMessageDialog(this, result, "提示", JOptionPane.WARNING_MESSAGE);
                return;
            }
            refreshTable(courseController.loadAllCourse());
            JOptionPane.showMessageDialog(this, result);
            // 切回列表卡片
            CardLayout cl = (CardLayout) CardPanel1.getLayout();
            cl.show(CardPanel1, "list");
            logger.info("修改课程成功，课程号：{}", courseId);
        } catch (Exception e) {
            logger.error("修改课程失败，课程号：{}", courseId, e);
            JOptionPane.showMessageDialog(this, "修改课程失败：" + e.getMessage(), "错误", JOptionPane.ERROR_MESSAGE);
        }
    }

    //这个方法用于处理添加课程界面的返回按钮点击事件
    private void btnAddBackActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout) CardPanel1.getLayout();
        cl.show(CardPanel1, "list"); // 切回课程列表卡片
    }

    private void btnListAddActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout) CardPanel1.getLayout();
        cl.show(CardPanel1, "add");
        // 清空输入框
        txtCourseID.setText("");
        txtCourseName.setText("");
        txtCourseCredit.setText("");
        txtCourseTeacher.setText("");
        txtCourseSemester.setText("");
    }

    //这个方法用于处理课程列表界面的修改按钮点击事件
    private void btnListUpdateActionPerformed(java.awt.event.ActionEvent evt) {
        // 校验是否选中行
        int selectedRow = TableCourse.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "请先选择要修改的课程！");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) TableCourse.getModel();
        // 逐个检查字段是否为null，避免空指针
        Object courseIdObj = model.getValueAt(selectedRow, 0);
        Object courseNameObj = model.getValueAt(selectedRow, 1);
        Object courseCreditObj = model.getValueAt(selectedRow, 2);
        Object courseTeacherObj = model.getValueAt(selectedRow, 3);
        Object courseSemesterObj = model.getValueAt(selectedRow, 4);


        if (courseIdObj == null || courseNameObj == null|| courseCreditObj== null|| courseTeacherObj== null|| courseSemesterObj== null) {
            JOptionPane.showMessageDialog(this, "选中的课程数据不完整，无法修改！");
            return;
        }

        // 回显选中行数据到修改界面
        txtCourseID1.setText(tableModel.getValueAt(selectedRow, 0).toString());
        txtCourseName1.setText(tableModel.getValueAt(selectedRow, 1).toString());
        txtCourseCredit1.setText(tableModel.getValueAt(selectedRow, 2).toString());
        txtCourseTeacher1.setText(tableModel.getValueAt(selectedRow, 3).toString());
        txtCourseSemester1.setText(tableModel.getValueAt(selectedRow, 4).toString());

        CardLayout cl = (CardLayout) CardPanel1.getLayout();
        cl.show(CardPanel1, "update"); // 切回课程列表卡片
    }

    //这个方法用于处理修改课程界面的返回按钮点击事件
    private void btnAddBack1ActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout) CardPanel1.getLayout();
        cl.show(CardPanel1, "list"); // 切回课程列表卡片
    }

    //这个方法用于处理课程列表界面的搜索按钮点击事件
    private void btnListCheckActionPerformed(java.awt.event.ActionEvent evt) {
        String keyword = jTextField1.getText().trim();
        if (courseController.isEmpty(keyword)) {
            // 关键词为空，加载所有课程
            courseController.loadAllCourse();
            return;
        }

        try {
            // 清空表格
            // 调用Service层模糊查询
            var courses = courseController.getCourseByCourseName(keyword);
            refreshTable(courses);
            logger.info("搜索课程成功，关键词：{}，共{}条", keyword, courses.size());
        } catch (Exception e) {
            logger.error("搜索课程失败，关键词：{}", keyword, e);
            refreshTable(courseController.loadAllCourse());
            JOptionPane.showMessageDialog(this, "搜索课程失败：" + e.getMessage(), "错误", JOptionPane.ERROR_MESSAGE);
        }
    }

    //这个方法用于处理课程列表界面的删除按钮点击事件
    private void btnListDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = TableCourse.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "请选择要删除的课程！");
            return;
        }
        String courseId = tableModel.getValueAt(selectedRow, 0).toString();
        int confirm = JOptionPane.showConfirmDialog(this, "确定删除？");
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            // 调用Controller层删除课程
            List<Map<String, Object>> updatedCourses = courseController.deleteCourseByCourseId(courseId);
            refreshTable(updatedCourses);
            JOptionPane.showMessageDialog(this, "课程删除成功！");
            logger.info("删除课程成功，课程号：{}", courseId);
        } catch (Exception e) {
            logger.error("删除课程失败，课程号：{}", courseId, e);
            refreshTable(courseController.loadAllCourse());
            JOptionPane.showMessageDialog(this, "删除课程失败：" + e.getMessage(), "错误", JOptionPane.ERROR_MESSAGE);
        }
    }

    // 刷新表格数据的方法
    private void refreshTable(List<Map<String, Object>> list) {
        DefaultTableModel model = (DefaultTableModel) TableCourse.getModel();
        model.setRowCount(0);
        if (list != null) {
            for (Map<String, Object> item : list) {
                model.addRow(new Object[]{
                        item.get("course_id"),
                        item.get("course_name"),
                        item.get("credit"),
                        item.get("teacher"),
                        item.get("semester")
                });
            }
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseManagerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel AddCard;
    private javax.swing.JPanel CardPanel1;
    private javax.swing.JPanel ListCard;
    private javax.swing.JTable TableCourse;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JPanel UPDATE;
    private javax.swing.JPanel UpdateCard;
    private javax.swing.JButton btnAddBack;
    private javax.swing.JButton btnAddBack1;
    private javax.swing.JButton btnAddSave;
    private javax.swing.JButton btnAddSave1;
    private javax.swing.JButton btnListAdd;
    private javax.swing.JButton btnListCheck;
    private javax.swing.JButton btnListDelete;
    private javax.swing.JButton btnListUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtCourseCredit;
    private javax.swing.JTextField txtCourseCredit1;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JTextField txtCourseID1;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCourseName1;
    private javax.swing.JTextField txtCourseSemester;
    private javax.swing.JTextField txtCourseSemester1;
    private javax.swing.JTextField txtCourseTeacher;
    private javax.swing.JTextField txtCourseTeacher1;
    // End of variables declaration
}

