package com.cjlu.ui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.cjlu.controller.ScoreController;
import com.cjlu.entity.Scores;

/**
 *
 * @author 24825
 */
public class ScoreManagerJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ScoreManagerJFrame
     */
    public ScoreManagerJFrame() {
        initComponents();
                controller = new ScoreController();
                refreshTable(controller.listAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        ScorePanel1 = new javax.swing.JPanel();
        ListCard = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnListCheck = new javax.swing.JButton();
        btnListAdd = new javax.swing.JButton();
        btnListUpdate = new javax.swing.JButton();
        btnListDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableScore = new javax.swing.JTable();
        AddCard = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtScoreID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCourseID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtScore = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtExamDate = new javax.swing.JTextField();
        btnAddBack = new javax.swing.JButton();
        btnAddSave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        UpdateCard = new javax.swing.JPanel();
        UPDATE = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtCourseID1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCourseName1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCourseCredit1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCourseTeacher1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCourseSemester1 = new javax.swing.JTextField();
        btnAddBack1 = new javax.swing.JButton();
        btnAddSave1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        ScorePanel1.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Search:");

        btnListCheck.setText("Check");
        btnListCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCheckActionPerformed(evt);
            }
        });

        btnListAdd.setText("Add");
        btnListAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListAddActionPerformed(evt);
            }
        });

        btnListUpdate.setText("Update");
        btnListUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListUpdateActionPerformed(evt);
            }
        });

        btnListDelete.setText("Delete");
        btnListDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListDeleteActionPerformed(evt);
            }
        });

        TableScore.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "ScoreID", "StudentID", "CouseID", "Score", "ExamDate"
                }
        ));
        jScrollPane1.setViewportView(TableScore);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
                TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(TopPanelLayout.createSequentialGroup()
                                                .addContainerGap(100, Short.MAX_VALUE)
                                                .addComponent(btnListAdd)
                                                .addGap(37, 37, 37)
                                                .addComponent(btnListUpdate)
                                                .addGap(31, 31, 31)
                                                .addComponent(btnListDelete))
                                        .addGroup(TopPanelLayout.createSequentialGroup()
                                                .addGap(56, 56, 56)
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListCheck)
                                .addGap(44, 44, 44))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        TopPanelLayout.setVerticalGroup(
                TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TopPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnListCheck)
                                        .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnListAdd)
                                        .addComponent(btnListUpdate)
                                        .addComponent(btnListDelete))
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout ListCardLayout = new javax.swing.GroupLayout(ListCard);
        ListCard.setLayout(ListCardLayout);
        ListCardLayout.setHorizontalGroup(
                ListCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TopPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ListCardLayout.setVerticalGroup(
                ListCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ListCardLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ScorePanel1.add(ListCard, "list");

        jLabel2.setText("ScoreID");

        txtScoreID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScoreIDActionPerformed(evt);
            }
        });

        jLabel3.setText("StudentID");

        jLabel4.setText("CourseID");

        jLabel5.setText("Score");

        jLabel6.setText("ExamDate");

        btnAddBack.setText("Back");
        btnAddBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBackActionPerformed(evt);
            }
        });

        btnAddSave.setText("Save");
        btnAddSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSaveActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel7.setText("ADD SCORE");

        javax.swing.GroupLayout AddCardLayout = new javax.swing.GroupLayout(AddCard);
        AddCard.setLayout(AddCardLayout);
        AddCardLayout.setHorizontalGroup(
                AddCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AddCardLayout.createSequentialGroup()
                                .addGroup(AddCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(AddCardLayout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(AddCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(AddCardLayout.createSequentialGroup()
                                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtScore))
                                                        .addGroup(AddCardLayout.createSequentialGroup()
                                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtCourseID))
                                                        .addGroup(AddCardLayout.createSequentialGroup()
                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtExamDate))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddCardLayout.createSequentialGroup()
                                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtScoreID, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddCardLayout.createSequentialGroup()
                                                                .addGap(94, 94, 94)
                                                                .addComponent(btnAddSave, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnAddBack, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(62, 62, 62))
                                                        .addGroup(AddCardLayout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtStudentID))))
                                        .addGroup(AddCardLayout.createSequentialGroup()
                                                .addGap(194, 194, 194)
                                                .addComponent(jLabel7)))
                                .addContainerGap(51, Short.MAX_VALUE))
        );
        AddCardLayout.setVerticalGroup(
                AddCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AddCardLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addGroup(AddCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtScoreID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(AddCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(AddCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(AddCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(AddCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(txtExamDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(AddCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAddBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAddSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71))
        );

        ScorePanel1.add(AddCard, "add");

        jLabel8.setText("ScoreID");

        txtCourseID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseID1ActionPerformed(evt);
            }
        });

        jLabel9.setText("StudentID");

        jLabel10.setText("CourseID");

        jLabel11.setText("Score");

        jLabel12.setText("ExamDate");

        btnAddBack1.setText("Back");
        btnAddBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBack1ActionPerformed(evt);
            }
        });

        btnAddSave1.setText("Update");
        btnAddSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSave1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel13.setText("UPDATE SCORE");

        javax.swing.GroupLayout UPDATELayout = new javax.swing.GroupLayout(UPDATE);
        UPDATE.setLayout(UPDATELayout);
        UPDATELayout.setHorizontalGroup(
                UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(UPDATELayout.createSequentialGroup()
                                .addGroup(UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(UPDATELayout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(UPDATELayout.createSequentialGroup()
                                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtCourseTeacher1))
                                                        .addGroup(UPDATELayout.createSequentialGroup()
                                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtCourseCredit1))
                                                        .addGroup(UPDATELayout.createSequentialGroup()
                                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtCourseSemester1))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UPDATELayout.createSequentialGroup()
                                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtCourseID1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UPDATELayout.createSequentialGroup()
                                                                .addGap(94, 94, 94)
                                                                .addComponent(btnAddSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btnAddBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(62, 62, 62))
                                                        .addGroup(UPDATELayout.createSequentialGroup()
                                                                .addComponent(jLabel9)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtCourseName1))))
                                        .addGroup(UPDATELayout.createSequentialGroup()
                                                .addGap(174, 174, 174)
                                                .addComponent(jLabel13)))
                                .addContainerGap(51, Short.MAX_VALUE))
        );
        UPDATELayout.setVerticalGroup(
                UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(UPDATELayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addGroup(UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(txtCourseID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(txtCourseName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(txtCourseCredit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(txtCourseTeacher1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(txtCourseSemester1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAddBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAddSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout UpdateCardLayout = new javax.swing.GroupLayout(UpdateCard);
        UpdateCard.setLayout(UpdateCardLayout);
        UpdateCardLayout.setHorizontalGroup(
                UpdateCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 507, Short.MAX_VALUE)
                        .addGroup(UpdateCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(UpdateCardLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        UpdateCardLayout.setVerticalGroup(
                UpdateCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 448, Short.MAX_VALUE)
                        .addGroup(UpdateCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(UpdateCardLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );

        ScorePanel1.add(UpdateCard, "update");

        getContentPane().add(ScorePanel1, "card5");

        pack();
    }// </editor-fold>

        private void btnListCheckActionPerformed(java.awt.event.ActionEvent evt) {
                String keyword = jTextField1.getText().trim();
                try {
                        List<Scores> list;
                        if (keyword.isEmpty()) {
                                list = controller.listAll();
                        } else {
                                // 简单策略：优先按学生ID整数解析，否则按课程名称查询
                                try {
                                        Integer sid = Integer.valueOf(keyword);
                                        list = controller.listByStudentId(sid);
                                } catch (NumberFormatException e) {
                                        list = controller.listByCourseName(keyword);
                                }
                        }
                        refreshTable(list);
                } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "查询失败: " + ex.getMessage());
                }
        }

    private void btnListAddActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout) ScorePanel1.getLayout();
        cl.show(ScorePanel1, "add");
        // 清空输入框
        txtScoreID.setText("");
        txtStudentID.setText("");
        txtCourseID.setText("");
        txtScore.setText("");
        txtExamDate.setText("");
    }

    private void btnListUpdateActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout) ScorePanel1.getLayout();
        cl.show(ScorePanel1, "update"); // 切回课程列表卡片
    }

        private void btnListDeleteActionPerformed(java.awt.event.ActionEvent evt) {
                int selectedRow = TableScore.getSelectedRow();
                if (selectedRow == -1) {
                        JOptionPane.showMessageDialog(this, "请选择要删除的成绩！");
                        return;
                }
                int confirm = JOptionPane.showConfirmDialog(this, "确定删除？");
                if (confirm == JOptionPane.YES_OPTION) {
                        try {
                                DefaultTableModel model = (DefaultTableModel) TableScore.getModel();
                                Object idObj = model.getValueAt(selectedRow, 0);
                                Integer scoreId = Integer.valueOf(String.valueOf(idObj));
                                controller.delete(scoreId);
                                refreshTable(controller.listAll());
                        } catch (Exception ex) {
                                JOptionPane.showMessageDialog(this, "删除失败: " + ex.getMessage());
                        }
                }
        }

    private void txtScoreIDActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnAddBackActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout) ScorePanel1.getLayout();
        cl.show(ScorePanel1, "list"); // 切回课程列表卡片
    }

        private void btnAddSaveActionPerformed(java.awt.event.ActionEvent evt) {
                // 获取输入数据（成绩模型：ScoreID 由后端生成也可手填，这里按服务层方法）
                String studentIdStr = txtStudentID.getText().trim();
                String courseCode = txtCourseID.getText().trim();
                String scoreStr = txtScore.getText().trim();
                String examDate = txtExamDate.getText().trim(); // 录入时暂不使用，更新时会写入实体

                if (studentIdStr.isEmpty() || courseCode.isEmpty() || scoreStr.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "必填项不能为空！");
                        return;
                }
                try {
                            Integer studentId = Integer.valueOf(studentIdStr);
                            Double score = Double.valueOf(scoreStr);
                            controller.add(studentId, courseCode, score);
                        refreshTable(controller.listAll());

                        CardLayout cl = (CardLayout) ScorePanel1.getLayout();
                        cl.show(ScorePanel1, "list");
                } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "保存失败: " + ex.getMessage());
                }
        }

    private void txtCourseID1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnAddBack1ActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout) ScorePanel1.getLayout();
        cl.show(ScorePanel1, "list"); // 切回课程列表卡片
    }

        private void btnAddSave1ActionPerformed(java.awt.event.ActionEvent evt) {
                int selectedRow = TableScore.getSelectedRow();
                if (selectedRow == -1) {
                        JOptionPane.showMessageDialog(this, "请先在列表选择一行进行更新！");
                        return;
                }
                try {
                        DefaultTableModel model = (DefaultTableModel) TableScore.getModel();
                        Integer scoreId = Integer.valueOf(String.valueOf(model.getValueAt(selectedRow, 0)));

                        String studentIdStr = txtCourseName1.getText().trim(); // 复用 UI 字段命名
                        String courseCode = txtCourseCredit1.getText().trim();
                        String scoreStr = txtCourseTeacher1.getText().trim();
                        String examDate = txtCourseSemester1.getText().trim();

                        Integer studentId = Integer.valueOf(studentIdStr);
                        Integer courseId = Integer.valueOf(courseCode);
                        Integer score = Integer.valueOf(scoreStr);

                        java.util.Date examDateVal = null;
                        if (!examDate.isEmpty()) {
                                try {
                                        examDateVal = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(examDate);
                                } catch (java.text.ParseException pe) {
                                        throw new IllegalArgumentException("考试日期格式应为 yyyy-MM-dd");
                                }
                        }

                        Scores s = new Scores();
                        s.setScoreId(scoreId);
                        s.setStudnetId(studentId); // 注意实体方法名为 setStudnetId
                        s.setCourseId(courseId);
                        s.setScore(score);
                        if (examDateVal != null) s.setExamDate(examDateVal);

                        controller.update(s);
                        refreshTable(controller.listAll());

                        CardLayout cl = (CardLayout) ScorePanel1.getLayout();
                        cl.show(ScorePanel1, "list");
                } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "更新失败: " + ex.getMessage());
                }
        }

        private void refreshTable(java.util.List<Scores> list) {
                DefaultTableModel model = (DefaultTableModel) TableScore.getModel();
                model.setRowCount(0);
                if (list == null) return;
                for (Scores s : list) {
                        model.addRow(new Object[]{
                                        s.getScoreId(),
                                        s.getStudentId(),
                                        s.getCourseId(),
                                        s.getScore(),
                                        s.getExamDate() == null ? "" : new java.text.SimpleDateFormat("yyyy-MM-dd").format(s.getExamDate())
                        });
                }
        }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreManagerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
        private ScoreController controller;
    private javax.swing.JPanel AddCard;
    private javax.swing.JPanel ListCard;
    private javax.swing.JPanel ScorePanel1;
    private javax.swing.JTable TableScore;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JPanel UPDATE;
    private javax.swing.JPanel UpdateCard;
    private javax.swing.JButton btnAddBack;
    private javax.swing.JButton btnAddBack1;
    private javax.swing.JButton btnAddSave;
    private javax.swing.JButton btnAddSave1;
    private javax.swing.JButton btnListAdd;
    private javax.swing.JButton btnListCheck;
    private javax.swing.JButton btnListDelete;
    private javax.swing.JButton btnListUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtCourseCredit1;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JTextField txtCourseID1;
    private javax.swing.JTextField txtCourseName1;
    private javax.swing.JTextField txtCourseSemester1;
    private javax.swing.JTextField txtCourseTeacher1;
    private javax.swing.JTextField txtExamDate;
    private javax.swing.JTextField txtScore;
    private javax.swing.JTextField txtScoreID;
    private javax.swing.JTextField txtStudentID;
    // End of variables declaration
}
