package com.cjlu.ui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.CardLayout;

/**
 *
 * @author 24825
 */
public class StatisticManageFrame extends javax.swing.JFrame {

    /**
     * Creates new form StatisticManageFrame
     */
    public StatisticManageFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        StatisticManage = new javax.swing.JPanel();
        MainCard = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        StudentStatisticCard = new javax.swing.JPanel();
        MatchStudentScrollPane1 = new javax.swing.JScrollPane();
        MatchStudentTable = new javax.swing.JTable();
        StudentConditionPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        MatchMajor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        MatchClass = new javax.swing.JTextField();
        btnStudentCheck = new javax.swing.JButton();
        btnStudentBack = new javax.swing.JButton();
        StudentTotalPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MatchStudentNumber = new javax.swing.JTextPane();
        ScoreStatisticCard = new javax.swing.JPanel();
        ScoreManageScrollPane = new javax.swing.JScrollPane();
        MatchScoreTable = new javax.swing.JTable();
        ScoreConditionPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtScoreMajor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtScoreClass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtScoreCourse = new javax.swing.JTextField();
        CheckButton = new javax.swing.JButton();
        btnScoreBack = new javax.swing.JButton();
        ScoreResultPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtAveScore = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMaxScore = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMinScore = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFailRate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        StatisticManage.setLayout(new java.awt.CardLayout());

        MainCard.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel11.setText("Please Choose Statistic Mode");

        jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 3, 18)); // NOI18N
        jButton1.setText("Student");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 3, 18)); // NOI18N
        jButton2.setText("Score");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainCardLayout = new javax.swing.GroupLayout(MainCard);
        MainCard.setLayout(MainCardLayout);
        MainCardLayout.setHorizontalGroup(
                MainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainCardLayout.createSequentialGroup()
                                .addGroup(MainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(MainCardLayout.createSequentialGroup()
                                                .addGap(182, 182, 182)
                                                .addComponent(jLabel11))
                                        .addGroup(MainCardLayout.createSequentialGroup()
                                                .addGap(252, 252, 252)
                                                .addGroup(MainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap(198, Short.MAX_VALUE))
        );
        MainCardLayout.setVerticalGroup(
                MainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainCardLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(106, Short.MAX_VALUE))
        );

        StatisticManage.add(MainCard, "Main");

        StudentStatisticCard.setLayout(new java.awt.BorderLayout());

        MatchStudentTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null}
                },
                new String [] {
                        "student_id", "name", "gender", "age", "major", "class_name", "admission_date", "phone", "email"
                }
        ));
        MatchStudentScrollPane1.setViewportView(MatchStudentTable);

        StudentStatisticCard.add(MatchStudentScrollPane1, java.awt.BorderLayout.CENTER);

        StudentConditionPanel.setLayout(new java.awt.GridLayout());

        jLabel2.setText("Major");
        StudentConditionPanel.add(jLabel2);
        StudentConditionPanel.add(MatchMajor);

        jLabel1.setText("Class：");
        StudentConditionPanel.add(jLabel1);
        StudentConditionPanel.add(MatchClass);

        btnStudentCheck.setText("Check");
        StudentConditionPanel.add(btnStudentCheck);

        btnStudentBack.setText("Back");
        btnStudentBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentBackActionPerformed(evt);
            }
        });
        StudentConditionPanel.add(btnStudentBack);

        StudentStatisticCard.add(StudentConditionPanel, java.awt.BorderLayout.PAGE_START);

        StudentTotalPanel.setLayout(new java.awt.GridLayout());

        jLabel4.setText("Total Amount Of Students Match");
        StudentTotalPanel.add(jLabel4);

        jScrollPane2.setViewportView(MatchStudentNumber);

        StudentTotalPanel.add(jScrollPane2);

        StudentStatisticCard.add(StudentTotalPanel, java.awt.BorderLayout.PAGE_END);

        StatisticManage.add(StudentStatisticCard, "Student");

        ScoreStatisticCard.setLayout(new java.awt.BorderLayout());

        MatchScoreTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "score_id", "student_id V", "course_id", "score", "exam_date"
                }
        ));
        ScoreManageScrollPane.setViewportView(MatchScoreTable);

        ScoreStatisticCard.add(ScoreManageScrollPane, java.awt.BorderLayout.CENTER);

        ScoreConditionPanel.setLayout(new java.awt.GridLayout(1, 6));

        jLabel3.setText("Major");
        ScoreConditionPanel.add(jLabel3);

        txtScoreMajor.setToolTipText("");
        ScoreConditionPanel.add(txtScoreMajor);

        jLabel5.setText("Class");
        ScoreConditionPanel.add(jLabel5);
        ScoreConditionPanel.add(txtScoreClass);

        jLabel6.setText("Course");
        ScoreConditionPanel.add(jLabel6);
        ScoreConditionPanel.add(txtScoreCourse);

        CheckButton.setText("Check");
        ScoreConditionPanel.add(CheckButton);

        btnScoreBack.setText("Back");
        btnScoreBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScoreBackActionPerformed(evt);
            }
        });
        ScoreConditionPanel.add(btnScoreBack);

        ScoreStatisticCard.add(ScoreConditionPanel, java.awt.BorderLayout.PAGE_START);

        ScoreResultPanel.setLayout(new java.awt.GridLayout(4, 4));

        jLabel7.setText("Average Score");
        ScoreResultPanel.add(jLabel7);
        ScoreResultPanel.add(txtAveScore);

        jLabel8.setText("Max Score");
        ScoreResultPanel.add(jLabel8);

        txtMaxScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxScoreActionPerformed(evt);
            }
        });
        ScoreResultPanel.add(txtMaxScore);

        jLabel9.setText("Min Score");
        ScoreResultPanel.add(jLabel9);
        ScoreResultPanel.add(txtMinScore);

        jLabel10.setText("Fail Rate");
        ScoreResultPanel.add(jLabel10);
        ScoreResultPanel.add(txtFailRate);

        ScoreStatisticCard.add(ScoreResultPanel, java.awt.BorderLayout.PAGE_END);

        StatisticManage.add(ScoreStatisticCard, "Score");

        getContentPane().add(StatisticManage, "card2");

        pack();
    }// </editor-fold>

    private void txtMaxScoreActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout) StatisticManage.getLayout();
        cl.show(StatisticManage, "Student");
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout) StatisticManage.getLayout();
        cl.show(StatisticManage, "Score");
    }

    private void btnStudentBackActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout)StatisticManage .getLayout();
        cl.show(StatisticManage, "Main"); // 切回主卡片
    }

    private void btnScoreBackActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout)StatisticManage .getLayout();
        cl.show(StatisticManage, "Main"); // 切回主卡片        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticManageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticManageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticManageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticManageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatisticManageFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton CheckButton;
    private javax.swing.JPanel MainCard;
    private javax.swing.JTextField MatchClass;
    private javax.swing.JTextField MatchMajor;
    private javax.swing.JTable MatchScoreTable;
    private javax.swing.JTextPane MatchStudentNumber;
    private javax.swing.JScrollPane MatchStudentScrollPane1;
    private javax.swing.JTable MatchStudentTable;
    private javax.swing.JPanel ScoreConditionPanel;
    private javax.swing.JScrollPane ScoreManageScrollPane;
    private javax.swing.JPanel ScoreResultPanel;
    private javax.swing.JPanel ScoreStatisticCard;
    private javax.swing.JPanel StatisticManage;
    private javax.swing.JPanel StudentConditionPanel;
    private javax.swing.JPanel StudentStatisticCard;
    private javax.swing.JPanel StudentTotalPanel;
    private javax.swing.JButton btnScoreBack;
    private javax.swing.JButton btnStudentBack;
    private javax.swing.JButton btnStudentCheck;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtAveScore;
    private javax.swing.JTextField txtFailRate;
    private javax.swing.JTextField txtMaxScore;
    private javax.swing.JTextField txtMinScore;
    private javax.swing.JTextField txtScoreClass;
    private javax.swing.JTextField txtScoreCourse;
    private javax.swing.JTextField txtScoreMajor;
    // End of variables declaration
}
