package com.cjlu.ui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Collections;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.cjlu.controller.Impl.ScoreControllerImpl;
import com.cjlu.controller.Impl.StudentControllerImpl;
import com.cjlu.entity.Scores;
import com.cjlu.entity.Student;

/**
 *
 * @author 24825
 */
public class StatisticManageFrame extends javax.swing.JFrame {

    private static final double PASS_THRESHOLD = 60.0;

    private final StudentControllerImpl studentController = new StudentControllerImpl();
    private final ScoreControllerImpl scoreController = new ScoreControllerImpl();
    private final SimpleDateFormat examDateFormat = new SimpleDateFormat("yyyy-MM-dd");

    /**
     * Creates new form StatisticManageFrame
     */
    public StatisticManageFrame() {
        initComponents();
        examDateFormat.setLenient(false);
        loadStudentData(null, null);
        refreshScoreTable(Collections.emptyList());
        clearScoreStatistics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        StatisticManage = new javax.swing.JPanel();
        MainCard = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        StudentStatisticCard = new javax.swing.JPanel();
        MatchStudentScrollPane1 = new javax.swing.JScrollPane();
        MatchStudentTable = new javax.swing.JTable();
        StudentConditionPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        MatchMajor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        MatchClass = new javax.swing.JTextField();
        btnStudentCheck = new javax.swing.JButton();
        btnStudentBack = new javax.swing.JButton();
        StudentTotalPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MatchStudentNumber = new javax.swing.JTextPane();
        ScoreStatisticCard = new javax.swing.JPanel();
        ScoreManageScrollPane = new javax.swing.JScrollPane();
        MatchScoreTable = new javax.swing.JTable();
        ScoreConditionPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtScoreMajor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtScoreClass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtScoreCourse = new javax.swing.JTextField();
        CheckButton = new javax.swing.JButton();
        btnScoreBack = new javax.swing.JButton();
        ScoreResultPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtAveScore = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMaxScore = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMinScore = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFailRate = new javax.swing.JTextField();

        // 关闭统计窗口时仅隐藏窗口，保持系统运行
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        StatisticManage.setLayout(new java.awt.CardLayout());

        MainCard.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel11.setText("Please Choose Statistic Mode");

        jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 3, 18)); // NOI18N
        jButton1.setText("Student");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 3, 18)); // NOI18N
        jButton2.setText("Score");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainCardLayout = new javax.swing.GroupLayout(MainCard);
        MainCard.setLayout(MainCardLayout);
        MainCardLayout.setHorizontalGroup(
                MainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainCardLayout.createSequentialGroup()
                                .addGroup(MainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(MainCardLayout.createSequentialGroup()
                                                .addGap(182, 182, 182)
                                                .addComponent(jLabel11))
                                        .addGroup(MainCardLayout.createSequentialGroup()
                                                .addGap(252, 252, 252)
                                                .addGroup(MainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap(198, Short.MAX_VALUE))
        );
        MainCardLayout.setVerticalGroup(
                MainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainCardLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(106, Short.MAX_VALUE))
        );

        StatisticManage.add(MainCard, "Main");

        StudentStatisticCard.setLayout(new java.awt.BorderLayout());

        MatchStudentTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null}
                },
                new String [] {
                        "student_id", "name", "gender", "age", "major", "class_name", "admission_date", "phone", "email"
                }
        ));
        MatchStudentScrollPane1.setViewportView(MatchStudentTable);

        StudentStatisticCard.add(MatchStudentScrollPane1, java.awt.BorderLayout.CENTER);

        StudentConditionPanel.setLayout(new java.awt.GridLayout());

        jLabel2.setText("Major");
        StudentConditionPanel.add(jLabel2);
        StudentConditionPanel.add(MatchMajor);

        jLabel1.setText("Class：");
        StudentConditionPanel.add(jLabel1);
        StudentConditionPanel.add(MatchClass);

        btnStudentCheck.setText("Check");
        btnStudentCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentCheckActionPerformed(evt);
            }
        });
        StudentConditionPanel.add(btnStudentCheck);

        btnStudentBack.setText("Back");
        btnStudentBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentBackActionPerformed(evt);
            }
        });
        StudentConditionPanel.add(btnStudentBack);

        StudentStatisticCard.add(StudentConditionPanel, java.awt.BorderLayout.PAGE_START);

        StudentTotalPanel.setLayout(new java.awt.GridLayout());

        jLabel4.setText("Total Amount Of Students Match");
        StudentTotalPanel.add(jLabel4);

        jScrollPane2.setViewportView(MatchStudentNumber);

        StudentTotalPanel.add(jScrollPane2);

        StudentStatisticCard.add(StudentTotalPanel, java.awt.BorderLayout.PAGE_END);

        StatisticManage.add(StudentStatisticCard, "Student");

        ScoreStatisticCard.setLayout(new java.awt.BorderLayout());

        MatchScoreTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "score_id", "student_id V", "course_id", "score", "exam_date"
                }
        ));
        ScoreManageScrollPane.setViewportView(MatchScoreTable);

        ScoreStatisticCard.add(ScoreManageScrollPane, java.awt.BorderLayout.CENTER);

        ScoreConditionPanel.setLayout(new java.awt.GridLayout(1, 6));

        jLabel3.setText("Major");
        ScoreConditionPanel.add(jLabel3);

        txtScoreMajor.setToolTipText("");
        ScoreConditionPanel.add(txtScoreMajor);

        jLabel5.setText("Class");
        ScoreConditionPanel.add(jLabel5);
        ScoreConditionPanel.add(txtScoreClass);

        jLabel6.setText("Course");
        ScoreConditionPanel.add(jLabel6);
        ScoreConditionPanel.add(txtScoreCourse);

        CheckButton.setText("Check");
        CheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckButtonActionPerformed(evt);
            }
        });
        ScoreConditionPanel.add(CheckButton);

        btnScoreBack.setText("Back");
        btnScoreBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScoreBackActionPerformed(evt);
            }
        });
        ScoreConditionPanel.add(btnScoreBack);

        ScoreStatisticCard.add(ScoreConditionPanel, java.awt.BorderLayout.PAGE_START);

        ScoreResultPanel.setLayout(new java.awt.GridLayout(4, 4));

        jLabel7.setText("Average Score");
        ScoreResultPanel.add(jLabel7);
        ScoreResultPanel.add(txtAveScore);

        jLabel8.setText("Max Score");
        ScoreResultPanel.add(jLabel8);

        txtMaxScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxScoreActionPerformed(evt);
            }
        });
        ScoreResultPanel.add(txtMaxScore);

        jLabel9.setText("Min Score");
        ScoreResultPanel.add(jLabel9);
        ScoreResultPanel.add(txtMinScore);

        jLabel10.setText("Fail Rate");
        ScoreResultPanel.add(jLabel10);
        ScoreResultPanel.add(txtFailRate);

        ScoreStatisticCard.add(ScoreResultPanel, java.awt.BorderLayout.PAGE_END);

        StatisticManage.add(ScoreStatisticCard, "Score");

        getContentPane().add(StatisticManage, "card2");

        pack();
    }// </editor-fold>

    //这个方法用于处理txtMaxScore的动作事件
    private void txtMaxScoreActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    //这个方法用于处理jButton1的动作事件
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout) StatisticManage.getLayout();
        cl.show(StatisticManage, "Student");
        loadStudentData(normalizeInput(MatchMajor.getText()), normalizeInput(MatchClass.getText()));
    }

    //这个方法用于处理jButton2的动作事件
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout) StatisticManage.getLayout();
        cl.show(StatisticManage, "Score");
        loadScoreData(normalizeInput(txtScoreMajor.getText()),
                normalizeInput(txtScoreClass.getText()),
                normalizeInput(txtScoreCourse.getText()));
    }

    //这个方法用于处理btnStudentBack的动作事件
    private void btnStudentBackActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout)StatisticManage .getLayout();
        cl.show(StatisticManage, "Main"); // 切回主卡片
    }

    //这个方法用于处理btnScoreBack的动作事件
    private void btnScoreBackActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout)StatisticManage .getLayout();
        cl.show(StatisticManage, "Main"); // 切回主卡片        // TODO add your handling code here:
    }

    // 这个方法用于处理 btnStudentCheck 的动作事件
    private void btnStudentCheckActionPerformed(java.awt.event.ActionEvent evt) {
        loadStudentData(normalizeInput(MatchMajor.getText()), normalizeInput(MatchClass.getText()));
    }

    // 这个方法用于处理 CheckButton 的动作事件
    private void CheckButtonActionPerformed(java.awt.event.ActionEvent evt) {
        loadScoreData(normalizeInput(txtScoreMajor.getText()),
                normalizeInput(txtScoreClass.getText()),
                normalizeInput(txtScoreCourse.getText()));
    }

    private void loadStudentData(String major, String className) {
        List<Student> students;
        try {
            students = studentController.getStudentsByMajorAndClass(major, className);
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(this, "加载学生数据失败: " + ex.getMessage());
            students = Collections.emptyList();
        }
        if (students == null) {
            students = Collections.emptyList();
        }
        refreshStudentTable(students);
    }

    private void refreshStudentTable(List<Student> students) {
        String[] columnNames = {"student_id", "name", "gender", "age", "major", "class_name", "admission_date", "phone", "email"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        if (students != null) {
            for (Student student : students) {
                if (student == null) {
                    continue;
                }
                model.addRow(new Object[] {
                        student.getStudentId(),
                        student.getName(),
                        student.getGender(),
                        student.getAge(),
                        student.getMajor(),
                        student.getClassName(),
                        formatDate(student.getAdmissionDate()),
                        student.getPhone(),
                        student.getEmail()
                });
            }
        }
        MatchStudentTable.setModel(model);
        int total = students == null ? 0 : students.size();
        MatchStudentNumber.setText(String.valueOf(total));
    }

    private void loadScoreData(String major, String className, String courseCode) {
        List<Scores> scores;
        try {
            scores = scoreController.searchByConditions(major, className, courseCode);
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(this, "加载成绩数据失败: " + ex.getMessage());
            scores = Collections.emptyList();
        }
        if (scores == null) {
            scores = Collections.emptyList();
        }
        refreshScoreTable(scores);
        updateScoreStatistics(scores);
    }

    private void refreshScoreTable(List<Scores> scores) {
        String[] columnNames = {"score_id", "student_id", "course_id", "score", "exam_date"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        if (scores != null) {
            for (Scores item : scores) {
                if (item == null) {
                    continue;
                }
                model.addRow(new Object[] {
                        item.getScoreId(),
                        item.getStudentId(),
                        item.getCourseCode(),
                        item.getScore(),
                        formatDate(item.getExamDate())
                });
            }
        }
        MatchScoreTable.setModel(model);
    }

    private void updateScoreStatistics(List<Scores> scores) {
        if (scores == null || scores.isEmpty()) {
            clearScoreStatistics();
            return;
        }
        double sum = 0.0;
        Double max = null;
        Double min = null;
        int validCount = 0;
        int failCount = 0;
        for (Scores score : scores) {
            if (score == null || score.getScore() == null) {
                continue;
            }
            double value = score.getScore();
            sum += value;
            validCount++;
            if (max == null || value > max) {
                max = value;
            }
            if (min == null || value < min) {
                min = value;
            }
            if (value < PASS_THRESHOLD) {
                failCount++;
            }
        }
        if (validCount == 0) {
            clearScoreStatistics();
            return;
        }
        double average = sum / validCount;
        double failRatePercent = (double) failCount / validCount * 100.0;
        txtAveScore.setText(String.format("%.2f", average));
        txtMaxScore.setText(max == null ? "" : String.format("%.2f", max));
        txtMinScore.setText(min == null ? "" : String.format("%.2f", min));
        txtFailRate.setText(String.format("%.2f%%", failRatePercent));
    }

    private void clearScoreStatistics() {
        txtAveScore.setText("");
        txtMaxScore.setText("");
        txtMinScore.setText("");
        txtFailRate.setText("");
    }

    private String normalizeInput(String raw) {
        if (raw == null) {
            return null;
        }
        String trimmed = raw.trim();
        return trimmed.isEmpty() ? null : trimmed;
    }

    private String formatDate(java.util.Date date) {
        if (date == null) {
            return "";
        }
        synchronized (examDateFormat) {
            return examDateFormat.format(date);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticManageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticManageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticManageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticManageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatisticManageFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton CheckButton;
    private javax.swing.JPanel MainCard;
    private javax.swing.JTextField MatchClass;
    private javax.swing.JTextField MatchMajor;
    private javax.swing.JTable MatchScoreTable;
    private javax.swing.JTextPane MatchStudentNumber;
    private javax.swing.JScrollPane MatchStudentScrollPane1;
    private javax.swing.JTable MatchStudentTable;
    private javax.swing.JPanel ScoreConditionPanel;
    private javax.swing.JScrollPane ScoreManageScrollPane;
    private javax.swing.JPanel ScoreResultPanel;
    private javax.swing.JPanel ScoreStatisticCard;
    private javax.swing.JPanel StatisticManage;
    private javax.swing.JPanel StudentConditionPanel;
    private javax.swing.JPanel StudentStatisticCard;
    private javax.swing.JPanel StudentTotalPanel;
    private javax.swing.JButton btnScoreBack;
    private javax.swing.JButton btnStudentBack;
    private javax.swing.JButton btnStudentCheck;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtAveScore;
    private javax.swing.JTextField txtFailRate;
    private javax.swing.JTextField txtMaxScore;
    private javax.swing.JTextField txtMinScore;
    private javax.swing.JTextField txtScoreClass;
    private javax.swing.JTextField txtScoreCourse;
    private javax.swing.JTextField txtScoreMajor;
    // End of variables declaration
}
