package com.cjlu.controller;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import com.cjlu.controller.Impl.ScoreControllerImpl;
import com.cjlu.dao.impl.ScoreDaoImpl;
import com.cjlu.dao.impl.StudentDaoImpl;
import com.cjlu.entity.Scores;
import com.cjlu.util.JDBCUtils;

class ScoreControllerTest {

    private static final AtomicInteger UNIQUE_SEQUENCE = new AtomicInteger(60000);

    private ScoreController controller;
    private ScoreDaoImpl scoreDao;
    private StudentDaoImpl studentDao;
    private List<Integer> createdStudentIds;

    @BeforeEach
    void setUp() throws Exception {
        controller = new ScoreControllerImpl();
        scoreDao = new ScoreDaoImpl();
        studentDao = new StudentDaoImpl();
        createdStudentIds = new ArrayList<>();
        ensureTableExists();
        ensureStudentTableExists();
        clearScoresTable();
    }

    @AfterEach
    void tearDown() throws Exception {
        clearScoresTable();
        deleteCreatedStudents();
    }

    @Test
    @DisplayName("add() should persist a score record that listAll() can retrieve")
    void addShouldPersistScore() {
        int studentId = createStudent();
        controller.add(studentId, "1001", 95.5);

        List<Scores> scores = controller.listAll();
        assertEquals(1, scores.size(), "listAll should return the inserted record");

        Scores saved = scores.get(0);
        assertNotNull(saved.getScoreId(), "scoreId should be generated by the database");
        assertEquals(studentId, saved.getStudentId());
        assertEquals("1001", saved.getCourseCode());
        assertEquals(95.5, saved.getScore(), 1e-6);
    }

    @Test
    @DisplayName("update() should apply new score, course, and exam date")
    void updateShouldModifyScore() {
        int studentId = createStudent();
        controller.add(studentId, "1002", 80.0);
        Scores original = controller.listAll().get(0);

        Date examDate = new Date();
        Scores updated = new Scores(original.getScoreId(), original.getStudentId(), "1003", 88.5, examDate);
        controller.update(updated);

        Scores fetched = controller.getById(original.getScoreId());
        assertEquals("1003", fetched.getCourseCode());
        assertEquals(88.5, fetched.getScore(), 1e-6);
        assertNotNull(fetched.getExamDate(), "examDate should be stored");
    }

    @Test
    @DisplayName("delete() should remove score by id")
    void deleteShouldRemoveScore() {
        int studentId = createStudent();
        controller.add(studentId, "1004", 70.0);
        Scores saved = controller.listAll().get(0);

        controller.delete(saved.getScoreId());

        assertEquals(0, controller.listAll().size(), "listAll should be empty after delete");
    }

    @Test
    @DisplayName("listByStudentId() should filter scores")
    void listByStudentIdShouldFilter() {
        int studentA = createStudent();
        int studentB = createStudent();
        controller.add(studentA, "1005", 85.0);
        controller.add(studentB, "1006", 82.0);

        List<Scores> filtered = controller.listByStudentId(studentA);
        assertEquals(1, filtered.size(), "Only one record belongs to the student");
        assertEquals("1005", filtered.get(0).getCourseCode());
    }

    @Test
    @DisplayName("listByCourseName() should filter scores")
    void listByCourseNameShouldFilter() {
        controller.add(createStudent(), "1007", 90.0);
        controller.add(createStudent(), "1007", 91.0);
        controller.add(createStudent(), "1008", 78.0);

        List<Scores> filtered = controller.listByCourseName("1007");
        assertEquals(2, filtered.size(), "Two records share the course code");
    }

    @Test
    @DisplayName("getById() should reject null id")
    void getByIdShouldRejectNull() {
        assertThrows(IllegalArgumentException.class, () -> controller.getById(null));
    }

    private void ensureTableExists() {
        if (!scoreDao.checkTableExists("SCORES")) {
            scoreDao.createScoreTable();
        }
    }

    private void ensureStudentTableExists() throws Exception {
        if (!tableExists("STUDENTS")) {
            studentDao.createStudentTable();
        }
    }

    private void clearScoresTable() throws Exception {
        try (Connection conn = JDBCUtils.getConnection();
                PreparedStatement ps = conn.prepareStatement("DELETE FROM scores")) {
            ps.executeUpdate();
        } catch (SQLException e) {
            if (e.getSQLState() != null && e.getSQLState().startsWith("42")) {
                scoreDao.createScoreTable();
            } else {
                throw e;
            }
        }
    }

    private int createStudent() {
        try (Connection conn = JDBCUtils.getConnection();
                PreparedStatement ps = conn.prepareStatement(
                        "INSERT INTO Students (name, age, gender, major, class, admission_date, phone, email) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                        Statement.RETURN_GENERATED_KEYS)) {
            int idx = UNIQUE_SEQUENCE.incrementAndGet();
            ps.setString(1, "Test Student " + idx);
            ps.setInt(2, 20);
            ps.setString(3, "M");
            ps.setString(4, "CS");
            ps.setString(5, "1A");
            ps.setDate(6, java.sql.Date.valueOf(LocalDate.now()));
            ps.setString(7, String.format("1%010d", idx));
            ps.setString(8, String.format("student%05d@example.com", idx));
            ps.executeUpdate();
            try (ResultSet rs = ps.getGeneratedKeys()) {
                if (rs.next()) {
                    int id = rs.getInt(1);
                    createdStudentIds.add(id);
                    return id;
                }
            }
            throw new IllegalStateException("Failed to obtain generated student ID");
        } catch (Exception e) {
            throw new RuntimeException("Failed to create test student", e);
        }
    }

    private boolean tableExists(String tableName) throws Exception {
        try (Connection conn = JDBCUtils.getConnection();
                ResultSet rs = conn.getMetaData().getTables(null, null, tableName, new String[] { "TABLE" })) {
            return rs.next();
        }
    }

    private void deleteCreatedStudents() throws Exception {
        if (createdStudentIds.isEmpty()) {
            return;
        }
        try (Connection conn = JDBCUtils.getConnection();
                PreparedStatement ps = conn.prepareStatement("DELETE FROM Students WHERE student_id = ?")) {
            for (Integer id : createdStudentIds) {
                ps.setInt(1, id);
                ps.addBatch();
            }
            ps.executeBatch();
        }
        createdStudentIds.clear();
    }
}
